title: "POD 23.MAR.PREP.2 - Javascript Jaguars"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  This is our portfolio website!
baseurl: "/" 
url: "/" 
twitter_username: mlhacks
github_username:  mlh-fellowship

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
plugins:
  - jekyll-maps
maps:
  google:
    marker_cluster:
      enabled: true

